### ISSUE TITLE
Can't create multi field

### ISSUE THREAD

**Issue by john-haus** [backdrop-contrib/multifield#38] opened 2020-09-10 17:43 UTC
Added this to a new site with (currently) very few modules.  Every time I try to create a multifield I get the following:

There was a problem creating field test: Cannot create a field with the name "field_test", which is reserved by entity type multifield.

Any ideas what this might be? Not much to go on I know.

**Comment by laryn** [comment] 2020-09-10 17:52
@padprint 
Did you add a `field_test` to a multifield and now are trying to add a different `field_test` to a content type? Try renaming the field/machine name  on the page where you are getting this.

**Comment by john-haus** [comment] 2020-09-10 17:56
No, this was trying to create a multifeld on a content type.  It would give the error, and when I look in the multfields list understructure, it is empty. "No multifield types available."

**Comment by laryn** [comment] 2020-09-10 18:14
Do you have the `Testing` module turned on? Spitballing but I do see a `field_test` in the codebase in the tests:
https://github.com/backdrop-contrib/multifield/search?q=field_test&unscoped_q=field_test

**Comment by john-haus** [comment] 2020-09-10 18:17
No sir. I've tried this with a couple different names, same result. I appreciate you looking though!

**Comment by laryn** [comment] 2020-09-10 18:24
I can't reproduce on a sandbox -- it let me add a multifield to a content type, with machine name `field_test`, and then add subfields (subfields not also named `field_test` of course). Which version are you using? Latest dev or one of the pre-releases? We should probably cut a real release...

**Comment by john-haus** [comment] 2020-09-10 19:12
Hey Laryn,
I'm using multifield-1.x-1.x , or at least trying to.  I've attempted to add the multifield to a content type that was created (without subsequent nodes being created) before the module was installed. I'm going to try creating a new content type to see what happens.

**Comment by findlabnet** [comment] 2021-02-09 20:02
I can confirm this bug. 
Backdrop 1.18.1 fresh install, module cloned from current state.
Error point is `function field_validate_field` - line 284 (core/modules/field/field.crud.inc) where `in_array` return false positive result.
If we use strict comparison - in_array with "true" as third parameter - field created without error.
I didn't full debug within multifield module, but maybe we need this correction in the core?

By the way, when new multifield created, as result we get an error message "This multifield does not have any subfields yet. Go to the manage subfields page to add some." I think it shouldn't be marked as an error but as a warning instead (line 886 in the file multifield.module).

**Comment by bobchristenson** [comment] 2021-09-16 13:07
Yup, same here on 1.19.1 - "Can't crate field_multi" when trying to add a multifield to a content type on a totally new install.  The field_test name isn't the problem...because for me, field_multi failed in the same way.

**Comment by oadaeh** [comment] 2021-10-04 14:38
The line that is causing this problem is 290 in multifield.module:
https://github.com/backdrop-contrib/multifield/blob/9617054d094e405c275eefe79bb366587c4a2d88/multifield.module#L290

That is in the `entity keys` element and is causing `in_array()` to return `TRUE`.

That line is repeated out one level, so I'm not sure if it's really needed in the `entity keys` sub-array or not.

The `configuration` element is not obviously looked for in the one place in core where the entity_info hook is invoked, so I don't know how it's used.

The only other contrib project I found that had that element in it, it was not in `entity keys`:
https://github.com/backdrop-contrib/multiple_email/blob/fe17186e184c48b86e91ca537dca04be48173c4a/multiple_email.module
So, I suspect it is not needed in `entity keys`.

**Comment by jenlampton** [comment] 2021-10-22 03:39
I confirmed that in the current 1.x-1.0.0-beta3 release this is not an issue, and that line is not within `entity keys`. I have assumed that was some kind of patch/diff mistake, and removed it.

**Closed as completed by jenlampton** 2021-10-22 03:39 UTC
